Improve development instructions
UCL/UKCORDEX-plot-explorer-dev pull request #63
Opened 2022-05-19 14:23 UTC by raquel-ucl

This contains a more updated and detailed version of the development instructions in the production repository.

2022-05-19 14:24 UTC, raquel-ucl commented
These are aimed mainly at @clairbarnes and @JamieJQuinn so small fixes and text changes can continue to be done after I have left the project. Take your time to make sure you understand these and ask for any clarification.

2022-05-19 14:58 UTC, giordano approved these changes

2022-05-23 15:59 UTC, JamieJQuinn requested changes
Beautiful! Suggested some tiny changes. Feel free to ignore if too nit-picky.

2022-05-23 15:59 UTC, JamieJQuinn commented on README.md
> +* npm (Last tested with npm 8.0.0)
Is it more useful to list which version the CI uses during its test deployment? It looks like we're running node version 16 but I don't know how the versions of npm and node relate...

2022-05-23 15:59 UTC, JamieJQuinn commented on README.md
> +* create-react-app
The list of the dependencies in the README could diverge from the [actual dependencies](https://github.com/UCL/UKCORDEX-plot-explorer-dev/blob/2184e1be0f3a43f7028918169e57fa4aa563399f/package.json#L6) pretty quickly, do we want to just link to `package.json`?

2022-05-23 15:59 UTC, JamieJQuinn commented on README.md
> +We are using [JamesIves/github-pages-deploy-action](https://github.com/JamesIves/github-pages-deploy-action) to deploy automatically using GH Actions, and [the npm gh-pages module](https://github.com
Is this a duplicate of line 32?

2022-05-23 15:59 UTC, JamieJQuinn commented on README.md
> +1. Create a new branch, e.g. `feature/about_us_section`.
Without an explicit contributor's guide, should we explicitly say we want branches named `<feature/bug>/<description>`?

2022-05-23 15:59 UTC, JamieJQuinn commented on README.md
> +Also note `--force` might be needed when dependencies prevent the project from building, but it's preferable to investigate the dependency issues with `npm audit` and resolve them avoiding force inst
```suggestion
Also note `--force` might be needed when dependencies prevent the project from building, but it's preferable to investigate the dependency issues with `npm audit` and resolve them avoiding force install.
```

2022-05-23 18:38 UTC, raquel-ucl commented on README.md
> +* npm (Last tested with npm 8.0.0)
There isn't a straight forward answer to this :)

The version of `npm` used in the CI is whichever the `ubuntu-latest` comes with. And I guess that'll change in the future, unless I force one version in particular, which might not be a good idea. The local npm version I've used was 8.0.0 at the time I wrote that message, but I now have 8.10.0 😬 Perhaps I should just remove the parenthesis.

The more important version is Node.js's. We are running one workflow for the tests which tries on several versions, and then for the deployment workflow we are using the latest, which is 16 as you say. We can't deploy on a matrix as they would all be deploying to the same GitHub Pages URL, and we wouldn't know which one of the three we'd be looking at! We could do a work around and deploy to three different paths within the same URL, but I didn't have enough time for that :(

The correlation between NPM and Node.js is also not straight forward. They are completely separate entities, but there are a number of versions of Node.js that a given version of NPM wouldn't support. 

I'll update the text in the parenthesis, but feel free to let me know if it's not clear and I should just remove it.

2022-05-23 18:38 UTC, raquelalegre commented on README.md
> +* create-react-app
Yep, that's a good idea, I'll do that!

2022-05-23 18:39 UTC, raquel-ucl commented on README.md
> +We are using [JamesIves/github-pages-deploy-action](https://github.com/JamesIves/github-pages-deploy-action) to deploy automatically using GH Actions, and [the npm gh-pages module](https://github.com
Whoops. Yes :)

2022-05-23 18:41 UTC, raquel-ucl commented
@JamieJQuinn have you tried running this locally? I think I'll wait to merge until you do so. We can do that together in the meeting we have scheduled, if you prefer :)

2022-05-23 18:52 UTC, raquel-ucl commented on README.md
> +* npm (Last tested with npm 8.0.0)
Oh, actually I just found out that an appropriate version of `npm` gets installed in the `actions/setup-node@v2` workflow step. So probably best to remove the parenthesis :)

2022-05-30 11:29 UTC, raquel-ucl commented
@JamieJQuinn and I had a pair programming sessions and he's gone through the local install well. @JamieJQuinn, are you happy with my latest changes after your review?

2022-05-30 14:59 UTC, JamieJQuinn reviewed
Perfect!

2022-05-30 14:59 UTC, JamieJQuinn approved these changes

2022-06-05 20:10 UTC, merged