Added acknowledgements of RSDG, CEDA, JASMIN
UCL/UKCORDEX-plot-explorer-dev pull request #67
Opened 2022-06-08 09:41 UTC by clairbarnes

2022-06-08 09:55 UTC, raquel-ucl commented on src/components/ExtraPages/About/Acknowledgements.js
> +          This plot explorer was developed by UCL's <a href='https://www.ucl.ac.uk/research-it-services/research-software-development'>
```suggestion
          This plot explorer was developed by UCL's <a href='https://www.ucl.ac.uk/advanced-research-computing/expertise/research-software-development'>
```

2022-06-08 09:56 UTC, raquel-ucl approved these changes

2022-06-08 19:20 UTC, raquel-ucl requested changes
These changes look good, but the tests are broken due to a dependency problem. Waiting for #68 to be merged and make sure the tests pass before approving again.

2022-06-09 11:20 UTC, raquel-ucl approved these changes

2022-06-09 11:23 UTC, raquel-ucl commented
Tests pass now 🥳 

However the font looks a bit too bold, and there's a space between the paragraphs that looks odd. I'll try and how to make it look more like the other sections.

2022-06-09 11:35 UTC, JamieJQuinn approved these changes
Beautifully acknowledged!

2022-06-09 15:36 UTC, merged